'use client';
import React, { useState, useEffect } from 'react';
import { apiFetch } from '../lib/api';
import { useToast } from './Toast';
import { Layers, PenTool, Sparkles, Loader2 } from 'lucide-react';

export default function AddAgentModal({ isOpen, onClose, onAdded }: { isOpen: boolean, onClose: () => void, onAdded: () => void }) {
  const [activeTab, setActiveTab] = useState<'custom'|'templates'|'ai_builder'>('custom');
  const [formData, setFormData] = useState({ name: '', role: '', description: '', model_name: 'gpt-4o' });
  const [prompt, setPrompt] = useState('');
  const [generating, setGenerating] = useState(false);
  const [templates, setTemplates] = useState<any[]>([]);
  const toast = useToast();

  useEffect(() => {
    if (isOpen && templates.length === 0) {
      apiFetch<any[]>('/agents/templates').then(data => {
        if(data) setTemplates(data);
      }).catch(console.error);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await apiFetch('/agents/register', {
        method: 'POST',
        body: JSON.stringify({ ...formData, owner_id: 'demo-user' })
      });
      toast('Agent registered successfully', 'ok');
      onAdded();
      onClose();
    } catch (err: any) {
      toast(err.message || 'Registration failed', 'err');
    }
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setGenerating(true);
    try {
      const data = await apiFetch<any>('/agents/create-from-prompt', {
        method: 'POST',
        body: JSON.stringify({ prompt })
      });
      setFormData({
        name: data.name,
        role: data.role,
        description: data.description,
        model_name: data.model_name || 'gpt-4o'
      });
      toast('Configuration generated by AI!', 'ok');
      setActiveTab('custom');
    } catch (err: any) {
      toast('AI generation failed: ' + err.message, 'err');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className={`overlay ${isOpen ? 'open' : ''}`} onClick={onClose}>
      <div className="modal" style={{ width: 440 }} onClick={e => e.stopPropagation()}>
        <div className="modal-hd">
          <div className="modal-title">REGISTER_NEURAL_AGENT</div>
          <button className="ms-btn ms-btn-g ms-btn-sm" onClick={onClose} style={{ width: 32, height: 32, padding: 0 }}>✕</button>
        </div>
        <div className="modal-body" style={{ padding: 0 }}>
          <div style={{ display: 'flex', borderBottom: '1px solid var(--bg3)' }}>
            <button 
              style={{ flex: 1, padding: '12px', background: activeTab === 'custom' ? 'var(--bg2)' : 'transparent', border: 'none', color: activeTab === 'custom' ? 'var(--text)' : 'var(--t3)', fontWeight: 800, fontSize: 11, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}
              onClick={() => setActiveTab('custom')}
            >
              <PenTool size={14} /> CUSTOM_BUILD
            </button>
            <button 
              style={{ flex: 1, padding: '12px', background: activeTab === 'templates' ? 'var(--bg2)' : 'transparent', border: 'none', color: activeTab === 'templates' ? 'var(--text)' : 'var(--t3)', fontWeight: 800, fontSize: 11, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}
              onClick={() => setActiveTab('templates')}
            >
              <Layers size={14} /> TEMPLATES
            </button>
            <button 
              style={{ flex: 1, padding: '12px', background: activeTab === 'ai_builder' ? 'var(--bg2)' : 'transparent', border: 'none', color: activeTab === 'ai_builder' ? 'var(--text)' : 'var(--t3)', fontWeight: 800, fontSize: 11, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}
              onClick={() => setActiveTab('ai_builder')}
            >
              <Sparkles size={14} className="text-[var(--blue)]" /> AI_BUILDER
            </button>
          </div>

          {activeTab === 'custom' && (
            <div style={{ padding: '24px' }}>
              <form onSubmit={handleSubmit} className="flex flex-col gap-6">
                <div className="fg">
                  <label className="fl">Agent Identity</label>
                  <input className="fi" required value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} placeholder="e.g. ResearchBot_v2" />
                </div>
                <div className="fg">
                  <label className="fl">Operational Role</label>
                  <input className="fi" required value={formData.role} onChange={e => setFormData({...formData, role: e.target.value})} placeholder="e.g. Core Web Researcher" />
                </div>
                <div className="fg">
                  <label className="fl">Inference Model</label>
                  <select className="fi" value={formData.model_name} onChange={e => setFormData({...formData, model_name: e.target.value})}>
                    <option value="gpt-4o">GPT-4o (Default)</option>
                    <option value="gpt-4o-mini">GPT-4o Mini (Efficiency)</option>
                    <option value="claude-3-5-sonnet">Claude 3.5 Sonnet (Logic)</option>
                  </select>
                </div>
                <div className="fg">
                  <label className="fl">Mission Directives</label>
                  <textarea className="fi" style={{ height: 100 }} value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} placeholder="Describe primary autonomous capabilities..." />
                </div>
                <div className="flex gap-4 mt-2">
                  <button type="button" className="ms-btn ms-btn-g" style={{ flex: 1 }} onClick={onClose}>ABORT</button>
                  <button type="submit" className="ms-btn ms-btn-p" style={{ flex: 1 }}>REGISTER_PROTOCOL</button>
                </div>
              </form>
            </div>
          )}

          {activeTab === 'templates' && (
            <div style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px', maxHeight: '400px', overflowY: 'auto' }}>
              {templates.map(t => (
                <div key={t.name} className="ms-glass-panel" style={{ padding: '16px', cursor: 'pointer', transition: 'border-color 0.2s' }} onClick={() => {
                  setFormData({ name: t.name, role: t.role, description: t.description, model_name: 'gpt-4o' });
                  setActiveTab('custom');
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 800, color: 'var(--text)' }}>{t.name}</div>
                      <div style={{ fontSize: 10, color: 'var(--yellow)', fontWeight: 700, marginTop: 4 }}>ROLE: {t.role.toUpperCase()}</div>
                    </div>
                    <button className="ms-btn ms-btn-p ms-btn-sm" style={{ padding: '0 8px', height: 24, fontSize: 10 }}>USE</button>
                  </div>
                  <div style={{ fontSize: 11, color: 'var(--t3)', marginTop: 8, lineHeight: 1.4 }}>{t.description}</div>
                </div>
              ))}
            </div>
          )}

          {activeTab === 'ai_builder' && (
            <div style={{ padding: '24px' }} className="flex flex-col gap-6">
               <div className="fg">
                  <label className="fl">Natural Language Prompt</label>
                  <textarea 
                    className="fi" 
                    style={{ height: 160, fontFamily: 'var(--mono)', fontSize: 12 }} 
                    value={prompt}
                    onChange={e => setPrompt(e.target.value)}
                    placeholder="Describe your ideal agent. e.g. 'Build me a security auditor that reviews Python code for SQL injection vulnerabilities and reports them with high severity.'"
                  />
               </div>
               <div className="flex gap-4">
                  <button type="button" className="ms-btn ms-btn-g" style={{ flex: 1 }} onClick={onClose}>ABORT</button>
                  <button 
                    className="ms-btn ms-btn-p" 
                    style={{ flex: 1 }} 
                    onClick={handleGenerate}
                    disabled={generating || !prompt.trim()}
                  >
                    {generating ? <Loader2 size={14} className="animate-spin mr-2" /> : <Sparkles size={14} className="mr-2" />}
                    {generating ? 'ARCHITECTING...' : 'GENERATE_PROTOCOL'}
                  </button>
               </div>
               <div className="text-[9px] text-[var(--t3)] italic text-center">
                  * Neural Architect will parse your prompt and auto-fill the custom build parameters.
               </div>
            </div>
          )}
        </div>
      </div>
    </div>

  );
}
