"""add_workflow_fields_to_goals

Revision ID: 40f73e9c1db5
Revises: 0001_initial_reset
Create Date: 2026-03-25 13:55:33.746883

"""
from alembic import op
import sqlalchemy as sa



revision = '40f73e9c1db5'
down_revision = '0001_initial_reset'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_name'), 'workflow_definitions', ['name'], unique=True)
    op.create_index(op.f('ix_workflow_definitions_user_id'), 'workflow_definitions', ['user_id'], unique=False)
    op.add_column('goals', sa.Column('workflow_type', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('workflow_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'workflow_json')
    op.drop_column('goals', 'workflow_type')
    op.drop_index(op.f('ix_workflow_definitions_user_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_name'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###

