"""add_dag_circuit_events

Revision ID: 693163ca5275
Revises: 8b918fa9fc11
Create Date: 2026-03-19 06:59:17.882338

"""
from alembic import op
import sqlalchemy as sa



revision = '693163ca5275'
down_revision = '8b918fa9fc11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breaker_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('state_from', sa.String(), nullable=False),
    sa.Column('state_to', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breaker_log_agent_id'), 'circuit_breaker_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_circuit_breaker_log_id'), 'circuit_breaker_log', ['id'], unique=False)
    op.create_table('dlq_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlq_events_agent_id'), 'dlq_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_dlq_events_id'), 'dlq_events', ['id'], unique=False)
    op.create_index(op.f('ix_dlq_events_task_id'), 'dlq_events', ['task_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('final_state', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_workflow_runs_run_id'), 'workflow_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_user_id'), 'workflow_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_name'), 'workflow_runs', ['workflow_name'], unique=False)
    op.create_table('agent_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('creator_name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_agent_templates_category'), 'agent_templates', ['category'], unique=False)
    op.create_index(op.f('ix_agent_templates_creator_id'), 'agent_templates', ['creator_id'], unique=False)
    op.create_index(op.f('ix_agent_templates_template_id'), 'agent_templates', ['template_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('hashed_secret', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=False)
    op.create_table('goals',
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('target_outcome', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('workflow_node_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_node_results_id'), 'workflow_node_results', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_node_results_node_id'), 'workflow_node_results', ['node_id'], unique=False)
    op.create_table('template_purchases',
    sa.Column('purchase_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('price_paid', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('stripe_payment_id', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.template_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_template_purchases_buyer_id'), 'template_purchases', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_template_purchases_template_id'), 'template_purchases', ['template_id'], unique=False)
    op.create_table('template_reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['agent_templates.template_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_template_reviews_template_id'), 'template_reviews', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_reviews_user_id'), 'template_reviews', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_usage_records_agent_id'), 'usage_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usage_records_metric'), 'usage_records', ['metric'], unique=False)
    op.create_index(op.f('ix_usage_records_period'), 'usage_records', ['period'], unique=False)
    op.create_index(op.f('ix_usage_records_task_id'), 'usage_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.add_column('agents', sa.Column('personality_config', sa.Text(), nullable=True))
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agents', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'users', ['owner_id'], ['user_id'])
    op.add_column('approval_requests', sa.Column('goal_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_approval_requests_goal_id'), 'approval_requests', ['goal_id'], unique=False)
    op.add_column('audit_logs', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['user_id'])
    op.add_column('events', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['user_id'])
    op.add_column('tasks', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('goal_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('thought_process', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('input_data', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('output_data', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_agent_id'), 'tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tasks_goal_id'), 'tasks', ['goal_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_goal_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_id'), table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'output_data')
    op.drop_column('tasks', 'input_data')
    op.drop_column('tasks', 'thought_process')
    op.drop_column('tasks', 'goal_id')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_column('events', 'user_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'user_id')
    op.drop_index(op.f('ix_approval_requests_goal_id'), table_name='approval_requests')
    op.drop_column('approval_requests', 'goal_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.alter_column('agents', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agents', 'personality_config')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_task_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_metric'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_agent_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_template_reviews_user_id'), table_name='template_reviews')
    op.drop_index(op.f('ix_template_reviews_template_id'), table_name='template_reviews')
    op.drop_table('template_reviews')
    op.drop_index(op.f('ix_template_purchases_template_id'), table_name='template_purchases')
    op.drop_index(op.f('ix_template_purchases_buyer_id'), table_name='template_purchases')
    op.drop_table('template_purchases')
    op.drop_index(op.f('ix_workflow_node_results_node_id'), table_name='workflow_node_results')
    op.drop_index(op.f('ix_workflow_node_results_id'), table_name='workflow_node_results')
    op.drop_table('workflow_node_results')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_agent_templates_template_id'), table_name='agent_templates')
    op.drop_index(op.f('ix_agent_templates_creator_id'), table_name='agent_templates')
    op.drop_index(op.f('ix_agent_templates_category'), table_name='agent_templates')
    op.drop_table('agent_templates')
    op.drop_index(op.f('ix_workflow_runs_workflow_name'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_user_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_run_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dlq_events_task_id'), table_name='dlq_events')
    op.drop_index(op.f('ix_dlq_events_id'), table_name='dlq_events')
    op.drop_index(op.f('ix_dlq_events_agent_id'), table_name='dlq_events')
    op.drop_table('dlq_events')
    op.drop_index(op.f('ix_circuit_breaker_log_id'), table_name='circuit_breaker_log')
    op.drop_index(op.f('ix_circuit_breaker_log_agent_id'), table_name='circuit_breaker_log')
    op.drop_table('circuit_breaker_log')
    # ### end Alembic commands ###

