"""Add parent_task_id to tasks

Revision ID: 8b918fa9fc11
Revises: a7fcd56710b1
Create Date: 2026-03-17 16:45:37.550554

"""
from alembic import op
import sqlalchemy as sa



revision = '8b918fa9fc11'
down_revision = 'a7fcd56710b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_task_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_task_id')
    # ### end Alembic commands ###

