"""Add agent role and description

Revision ID: a7fcd56710b1
Revises: ed9b73ecfca3
Create Date: 2026-03-17 16:29:36.483939

"""
from alembic import op
import sqlalchemy as sa



revision = 'a7fcd56710b1'
down_revision = 'ed9b73ecfca3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('role', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'description')
    op.drop_column('agents', 'role')
    # ### end Alembic commands ###

