"""Add node_id to tasks

Revision ID: bd444e96e35c
Revises: 87a0d6474d01
Create Date: 2026-03-31 12:23:28.735558

"""
from alembic import op
import sqlalchemy as sa



revision = 'bd444e96e35c'
down_revision = '87a0d6474d01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('node_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_node_id'), 'tasks', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_node_id'), table_name='tasks')
    op.drop_column('tasks', 'node_id')
    # ### end Alembic commands ###

