"""add_personality_config

Revision ID: bf824252f17b
Revises: 693163ca5275
Create Date: 2026-03-19 07:01:00.379537

"""
from alembic import op
import sqlalchemy as sa



revision = 'bf824252f17b'
down_revision = '693163ca5275'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

