"""add_cost_fields_v2

Revision ID: ca6c6ebca164
Revises: bf824252f17b
Create Date: 2026-03-20 10:47:36.681346

"""
from alembic import op
import sqlalchemy as sa



revision = 'ca6c6ebca164'
down_revision = 'bf824252f17b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('base_cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('model_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'model_used')
    op.drop_column('tasks', 'cost')
    op.drop_column('agents', 'base_cost')
    op.drop_column('agents', 'model_name')
    # ### end Alembic commands ###

