import asyncio
import uuid
import datetime
import random
import sqlalchemy as sa
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from app.config import settings
from app.models.agent import Agent
from app.models.task import Task
from app.models.trace import Trace
from app.models.user import User

async def seed():
    engine = create_async_engine(settings.DATABASE_URL)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    async with async_session() as db:
        # 1. Get ANY Agents
        res = await db.execute(sa.select(Agent))
        agents = res.scalars().all()
        if not agents:
            print("No agents found in the entire database. Run diagnostics first.")
            return

        user_id = "demo-user"

        # 3. Create Tasks
        task_types = [
            "Search for latest AI news",
            "Summarize research paper on LLMs",
            "Generate Python script for data visualization",
            "Audit security logs for breaches",
            "Write blog post about AgentCloud"
        ]
        
        for i in range(12):
            agent = random.choice(agents)
            task_id = str(uuid.uuid4())
            status = random.choice(["completed", "completed", "completed", "failed", "in_progress"])
            created_at = datetime.datetime.utcnow() - datetime.timedelta(hours=random.randint(0, 24))
            
            task = Task(
                task_id=task_id,
                user_id=user_id,
                agent_id=agent.agent_id,
                payload=random.choice(task_types),
                status=status,
                result="Sample execution result generated by seeder." if status == "completed" else None,
                created_at=created_at,
                priority_level=random.randint(1, 10)
            )
            db.add(task)
            
            # 4. Create Traces for completed tasks
            if status == "completed":
                for step in ["Initialization", "Reasoning", "Tool Execution", "Aggregation"]:
                    trace = Trace(
                        trace_id=str(uuid.uuid4()),
                        task_id=task_id,
                        agent_id=agent.agent_id,
                        step=step,
                        metadata_info={"log": f"Diagnostic log for step {step}"},
                        created_at=created_at + datetime.timedelta(minutes=random.randint(1, 5))
                    )
                    db.add(trace)

        await db.commit()
        print("Successfully seeded 12 tasks and associated traces.")

import sqlalchemy as sa
if __name__ == "__main__":
    asyncio.run(seed())
