"""add_missing_updated_at_to_agents

Revision ID: 87a0d6474d01
Revises: 60e83b8ae24f
Create Date: 2026-03-27 08:52:46.088628

"""
from alembic import op
import sqlalchemy as sa



revision = '87a0d6474d01'
down_revision = '60e83b8ae24f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_templates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_audit_logs_agent_id'), 'audit_logs', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'agents', ['agent_id'], ['agent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_agent_id'), table_name='audit_logs')
    op.drop_column('agents', 'updated_at')
    op.drop_column('agent_templates', 'updated_at')
    # ### end Alembic commands ###

